version: "3.0"

services:
  service:
    env_file:
      - ".docker-compose-env"
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    command: [ "pipenv", "run", "uvicorn", "--host", "0.0.0.0", "--port", "9000", "service:app" ]
    volumes:
      - ./data/:/opt/data-generator-service/data
